baseurl = "http://www.json.blog"
languageCode = "en-us"
title = "JSONBecker"
theme = 'jsonbecker'
paginate = 20
[permalinks]
  post = "/:year/:month/:slug"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  googleAnalytics=  "UA-40920108-1"
